# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BFit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BFit
	pod 'Alamofire'
	pod 'SDWebImage'
	pod 'RxSwift'
	pod 'RxCocoa' 
	pod 'ProgressHUD'
	pod 'LanguageManager-iOS'

  target 'BFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
